# Base configuration for routes.yaml

- route: /
  handler: '%kernel.project_dir%/README.md'
  name: homepage

- route: error
  handler: '%kernel.project_dir%/templates/error.html.twig'
  name: errorpage

- route: /examples
  handler: 'Derafu\ExamplesForm\ExamplesController::index'
  name: examples

- route: /examples/{id}
  handler: 'Derafu\ExamplesForm\ExamplesController::show'
  name: example
