# Base configuration for services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Derafu\ExamplesForm\ExamplesController:
        public: true

    Psr\Http\Server\RequestHandlerInterface:
        class: Derafu\Http\Service\RequestHandler
        public: true
        arguments:
            $middlewares:
                - '@Derafu\Http\Middleware\StaticFilesMiddleware'
                - '@Derafu\Http\Middleware\RequestFactoryMiddleware'
                - '@Derafu\Http\Middleware\RouterMiddleware'
                - '@Derafu\Http\Middleware\DispatcherMiddleware'
                - '@Derafu\Http\Middleware\ResponseNormalizerMiddleware'

    Derafu\Http\Middleware\StaticFilesMiddleware:
        arguments:
            $directory: '%kernel.project_dir%/public/static'
    Derafu\Http\Middleware\RequestFactoryMiddleware: ~
    Derafu\Http\Middleware\RouterMiddleware: ~
    Derafu\Http\Middleware\DispatcherMiddleware: ~
    Derafu\Http\Middleware\ResponseNormalizerMiddleware: ~

    Derafu\Http\Contract\RequestFactoryInterface:
        class: Derafu\Http\Factory\RequestFactory

    Derafu\Routing\Contract\RouterInterface:
        class: Derafu\Routing\Router
        arguments:
            $parsers:
                - '@Derafu\Routing\Parser\StaticParser'
                - '@Derafu\Routing\Parser\DynamicParser'
                - '@Derafu\Routing\Parser\FileSystemParser'
            $routes: '%routes%'

    Derafu\Routing\Parser\StaticParser: ~

    Derafu\Routing\Parser\DynamicParser: ~

    Derafu\Routing\Parser\FileSystemParser:
        arguments:
            $directories:
                - '%kernel.project_dir%/templates/pages'
            $extensions: ['.html.twig', '.md', '.php']

    Derafu\Http\Contract\DispatcherInterface:
        class: Derafu\Http\Service\Dispatcher

    Derafu\Http\Contract\ProblemHandlerInterface:
        class: Derafu\Http\Service\ProblemHandler
        lazy: true

    Derafu\Http\Contract\ProblemFactoryInterface:
        class: Derafu\Http\Factory\ProblemFactory
        lazy: true

    Derafu\Http\Contract\SafeThrowableFactoryInterface:
        class: Derafu\Http\Factory\SafeThrowableFactory
        lazy: true

    Derafu\Renderer\Contract\RendererInterface:
        factory: ['Derafu\Renderer\Factory\RendererFactory', 'create']
        lazy: true
        arguments:
            $options:
                engines: ['twig', 'markdown']
                paths:
                    - '%kernel.project_dir%/templates'
                    - '%kernel.project_dir%/resources/templates'
                    - '%kernel.project_dir%/vendor/derafu/twig/resources/templates'
                extensions:
                    - '@Derafu\Form\Renderer\FormTwigExtension'

    Derafu\Form\Renderer\FormTwigExtension: ~

    Derafu\Form\Contract\Renderer\FormRendererInterface:
        class: Derafu\Form\Renderer\FormRenderer

    Derafu\Form\Contract\Renderer\ElementRendererRegistryInterface:
        class: Derafu\Form\Renderer\ElementRendererRegistry
        arguments:
            $renderers: '@Derafu\Form\Renderer\ElementRendererProvider'

    Derafu\Form\Renderer\ElementRendererProvider: ~

    Derafu\Form\Contract\Renderer\WidgetRendererRegistryInterface:
        class: Derafu\Form\Renderer\WidgetRendererRegistry
        arguments:
            $renderers: '@Derafu\Form\Renderer\WidgetRendererProvider'

    Derafu\Form\Renderer\WidgetRendererProvider: ~

    Derafu\Form\Contract\Factory\FormFactoryInterface:
        class: Derafu\Form\Factory\FormFactory

    Derafu\Form\Contract\Type\TypeResolverInterface:
        class: Derafu\Form\Type\TypeResolver

    Derafu\Form\Contract\Type\TypeRegistryInterface:
        class: Derafu\Form\Type\TypeRegistry
        arguments:
            $types: '@Derafu\Form\Contract\Type\TypeProviderInterface'

    Derafu\Form\Contract\Type\TypeProviderInterface:
        class: Derafu\Form\Type\TypeProvider
